### ISSUE TITLE
COM Exception

### ISSUE THREAD

**Issue by pitermarx** [SharpeRAD/Cake.IIS#42]
I'm not able to google myself out of this. Maybe you have seen this before.

my cake script is just this

```
#addin "Cake.IIS"
StartPool("MachineName", "PoolName");
```
```
Error: System.AggregateException: One or more errors occurred. --->
System.AggregateException: One or more errors occurred. ---> 
System.Runtime.InteropServices.COMException: Retrieving the COM class factory for remote component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} from machine <machineName> failed due to the following error: 800703fa <machineName>.

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Web.Administration.ConfigurationManager.CreateAdminManager[TClass,TInterface](WebConfigurationMap webConfigMap, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateWritableAdminManager(WebConfigurationMap webConfigMap, String configPathToEdit, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateConfiguration(WebConfigurationMap configMap, String configPathToEdit, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetConfiguration(String rawConfigurationPath, String cacheKey, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetApplicationHostConfiguration()
   at Microsoft.Web.Administration.ServerManager.ApplicationPoolsSectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.ApplicationPoolCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Cake.IIS.ApplicationPoolManager.Start(String name)
   at Cake.IIS.ApplicationPoolAliases.StartPool(ICakeContext context, String server, String name)
   at Submission#0.StartPool(String server, String name)
   at Submission#0.<<Initialize>>d__0.MoveNext()

**Comment by pitermarx** [comment]
I couldn't find the cause, but I restarted the "MachineName" and now it works...
Sorry to bother
