### ISSUE TITLE
StopPool with remote location throws null exception

### ISSUE THREAD

**Issue by punkster91** [SharpeRAD/Cake.IIS#53]
Cake version = 0.30.0
Cake.IIS version = 0.4.1

When specifying a remote location for these functions I get a null exception.
`DeletePool("127.0.0.1", "Test") - Fail`
`StopPool("localhost", "Test") - Fail`

```c#
Error: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.Administration.ConfigurationManager.CreateWritableAdminManager(WebConfigurationMap webConfigMap, String configPathToEdit, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateConfiguration(WebConfigurationMap configMap, String configPathToEdit, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetConfiguration(String rawConfigurationPath, String cacheKey, Boolean isAdminConfig, Boolean isRedirectionConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetApplicationHostConfiguration()
   at Microsoft.Web.Administration.ServerManager.ApplicationPoolsSectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.ApplicationPoolCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Cake.IIS.ApplicationPoolManager.Stop(String name)
   at Cake.IIS.ApplicationPoolAliases.StopPool(ICakeContext context, String server, String name)
   at Submission#0.StopPool(String server, String name)
   at Submission#0.<<Initialize>>b__0_1()
```

The functions work if you don't use the remote-location at all.
`DeletePool( "Test") - Success`
`StopPool("Test") - Success`

**Comment by pitermarx** [comment]
same here

**Comment by pitermarx** [comment]
from [here](https://forums.iis.net/post/2135998.aspx) it seems that the IIS nuget package is not compatible with remote usage.

> I think the NuGet package was only released for IIS Administration REST API,
> https://github.com/Microsoft/IIS.Administration
> Thus, the NuGet version is internally different from the version shipped with Windows.

**Comment by SmGG** [comment]
I came into this problem too!
Can anybody help us with this, this is painful TAT

**Comment by nrukavkov** [comment]
The same problem. Does anybody know how to fix it?
